#!/usr/bin/env bash
# Phase 5d - train the subject LoRA with musubi-tuner, on one GPU.
#
# WHY THE BASE T2V CHECKPOINT AND NOT THE VACE ONE
# musubi-tuner has no VACE task - the string "vace" does not appear anywhere in
# its source at the pinned revision - so training happens against Wan2.1 T2V
# 1.3B and the result is loaded onto VACE 1.3B at inference. That is sound here,
# and it was checked rather than assumed: every one of the 825 tensors in the
# T2V checkpoint is present in the VACE checkpoint under an identical name and
# with an identical shape, and VACE adds 439 tensors of its own on top. A LoRA
# over the backbone therefore lands on tensors that exist, unchanged, in the
# model that will actually run. What it cannot reach is VACE's own blocks.
#
# WHY THESE WEIGHTS AND NOT THE PIPELINE'S
# The ComfyUI copies are the wrong formats. Its text encoder is fp8_scaled,
# which musubi explicitly does not support, and its DiT is the VACE variant.
# The VAE is the same file and is shared, not downloaded twice.
#
# WHAT THE TRIGGER TOKEN OBLIGES
# The captions in the dataset are the trigger token and nothing else. A LoRA
# trained this way does nothing unless the token appears in the generation
# prompt, so enabling `model.lora` in a config without adding the token to
# `prompt.positive` produces an unchanged result that looks like a failed
# experiment. The token is printed at the end of this script for that reason.
#
# Rule 5 does not apply: this trains on stills, and touches no video.
#
#   scripts/train_subject_lora.sh [--epochs N] [--resolution N] [--name NAME]
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$(pwd)"

MUSUBI_DIR="${MUSUBI_DIR:-/workspace/musubi-tuner}"
WAN_TRAIN_MODELS="${WAN_TRAIN_MODELS:-/workspace/wan_train_models}"
# bf16, not the fp16 twin sitting beside it: the trainer asserts that the DiT's
# dtype and --mixed_precision agree, so an fp16 checkpoint forces fp16 training,
# and fp16 is the less stable of the two for a small-sample LoRA. The inference
# checkpoint stays fp16 - LoRA weights are cast at load and need not match it.
DIT="${DIT:-$WAN_TRAIN_MODELS/split_files/diffusion_models/wan2.1_t2v_1.3B_bf16.safetensors}"
T5="${T5:-$WAN_TRAIN_MODELS/models_t5_umt5-xxl-enc-bf16.pth}"
VAE="${VAE:-$ROOT/ComfyUI/models/vae/wan_2.1_vae.safetensors}"
DATASET="${DATASET:-$ROOT/intermediate/lora_dataset}"
OUT_DIR="${OUT_DIR:-$ROOT/intermediate/lora_out}"

EPOCHS=140          # 9 images at batch 1 -> ~1260 steps
SAVE_EVERY=20       # a checkpoint every ~180 steps, so the best one can be
                    # CHOSEN by measurement instead of hoped for
RESOLUTION=384
NAME="subject_1p3b_v1"
DIM=32              # kohya's documented Wan example; alpha stays at the default
LR=2e-4

while [ $# -gt 0 ]; do
  case "$1" in
    --epochs)     EPOCHS="$2"; shift 2 ;;
    --resolution) RESOLUTION="$2"; shift 2 ;;
    --name)       NAME="$2"; shift 2 ;;
    --dim)        DIM="$2"; shift 2 ;;
    --lr)         LR="$2"; shift 2 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

LOG="$ROOT/logs/train_${NAME}.log"
mkdir -p "$ROOT/logs" "$OUT_DIR"

say() { echo "[$(date -u +%FT%TZ)] $*" | tee -a "$LOG"; }

# Rule 3: no silent CPU fallback. A LoRA that trains on CPU does not finish.
if ! nvidia-smi --query-gpu=name --format=csv,noheader >/dev/null 2>&1; then
  echo "FATAL: no CUDA device. Training on CPU is not a slower run, it is no run." >&2
  exit 1
fi

PY="$MUSUBI_DIR/.venv/bin/python"
for f in "$PY" "$DIT" "$T5" "$VAE"; do
  [ -e "$f" ] || { echo "FATAL: missing $f" >&2; exit 1; }
done

TRAIN_DIR="$DATASET/train"
n_img=$(find "$TRAIN_DIR" -name '*.png' | wc -l | tr -d ' ')
n_cap=$(find "$TRAIN_DIR" -name '*.txt' | wc -l | tr -d ' ')
[ "$n_img" -gt 0 ] || { echo "FATAL: no training crops in $TRAIN_DIR. Run scripts/make_lora_dataset.py first." >&2; exit 1; }
if [ "$n_img" -ne "$n_cap" ]; then
  echo "FATAL: $n_img crop(s) but $n_cap caption(s). musubi silently skips an" >&2
  echo "image with no caption, so the set that trains would not be the set exported." >&2
  exit 1
fi
TRIGGER="$(cat "$(find "$TRAIN_DIR" -name '*.txt' | sort | head -1)")"
n_trig=$(cat "$TRAIN_DIR"/*.txt | sort -u | wc -l | tr -d ' ')
[ "$n_trig" -eq 1 ] || { echo "FATAL: captions are not identical across the set ($n_trig distinct)." >&2; exit 1; }

say "musubi $(git -C "$MUSUBI_DIR" describe --tags --always) | $n_img image(s) | ${RESOLUTION}px | dim $DIM | lr $LR | $EPOCHS epochs"
say "trigger token: '$TRIGGER'"

TOML="$DATASET/dataset.toml"
cat > "$TOML" <<EOF
# Generated by scripts/train_subject_lora.sh - edits here are overwritten.
[general]
resolution = [$RESOLUTION, $RESOLUTION]
caption_extension = ".txt"
batch_size = 1
enable_bucket = true
bucket_no_upscale = false

[[datasets]]
image_directory = "$TRAIN_DIR"
cache_directory = "$DATASET/cache"
num_repeats = 1
EOF

# Caching is idempotent: both steps skip an item whose cache file already
# exists, so a re-run after an interruption resumes rather than redoing (rule 8).
say "caching latents"
"$PY" "$MUSUBI_DIR/src/musubi_tuner/wan_cache_latents.py" \
    --dataset_config "$TOML" --vae "$VAE" 2>&1 | tee -a "$LOG"

say "caching text encoder outputs"
"$PY" "$MUSUBI_DIR/src/musubi_tuner/wan_cache_text_encoder_outputs.py" \
    --dataset_config "$TOML" --t5 "$T5" --batch_size 4 2>&1 | tee -a "$LOG"

say "training"
"$MUSUBI_DIR/.venv/bin/accelerate" launch \
    --num_cpu_threads_per_process 1 --mixed_precision bf16 \
    "$MUSUBI_DIR/src/musubi_tuner/wan_train_network.py" \
    --task t2v-1.3B \
    --dit "$DIT" \
    --dataset_config "$TOML" \
    --sdpa --mixed_precision bf16 \
    --optimizer_type adamw8bit --learning_rate "$LR" \
    --gradient_checkpointing \
    --max_data_loader_n_workers 2 --persistent_data_loader_workers \
    --network_module networks.lora_wan --network_dim "$DIM" \
    --timestep_sampling shift --discrete_flow_shift 3.0 \
    --max_train_epochs "$EPOCHS" --save_every_n_epochs "$SAVE_EVERY" \
    --seed 42 \
    --output_dir "$OUT_DIR" --output_name "$NAME" 2>&1 | tee -a "$LOG"

# Rule 4: a zero exit proves it ran, not that the file is usable.
FINAL="$OUT_DIR/$NAME.safetensors"
[ -f "$FINAL" ] || { echo "FATAL: training exited 0 but $FINAL does not exist." >&2; exit 1; }
"$PY" - "$FINAL" <<'EOF' | tee -a "$LOG"
import sys, torch
from safetensors.torch import load_file
sd = load_file(sys.argv[1])
n = len(sd)
finite = all(torch.isfinite(v).all() for v in sd.values())
nonzero = sum(1 for v in sd.values() if v.abs().sum() > 0)
print(f"LoRA tensors: {n}, all finite: {finite}, non-zero: {nonzero}")
if not n or not finite or nonzero < n // 2:
    sys.exit("FATAL: the LoRA is empty, non-finite, or mostly zero - it did not train.")
EOF

say "checkpoints:"
ls -1 "$OUT_DIR"/${NAME}*.safetensors | tee -a "$LOG"
say "done. The trigger token '$TRIGGER' MUST appear in prompt.positive for this LoRA to do anything."
